name = "droughtmodel"
version = "0.1.0"
license = "MIT"
author = "Khadar Daahir"
maintainer = "khadar@glasgow.ac.uk"
copyright = "Copyright 2025, Khadar"

[build]
external-modules = ["netcdf"]
auto-executables = true
module-naming = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
fsml = { git = "https://github.com/sebastian-mutz/fsml.git" }
stdlib = "*"

[[executable]]
name = "HistoricalSPI"
source-dir = "app"
main = "analysis_historical.f90"