name = "droughtmodel"
version = "0.1.0"
license = "MIT"
author = "Khadar Daahir"

[build]
external-modules = ["netcdf"]
link = ["netcdff"]

[[executable]]
name = "main"
source-dir = "app"
main = "main.f90"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"